- archetypes/operator.de.md
- archetypes/operator.en.md
- content/operator/zsr/index.de.md
- content/operator/zsr/index.en.md
@therobrob was denkst du davon? Ich hatte gehofft, dass für den Nutzer so vielleicht klarer ist, wieso eine Warnung bei einer Zugkategorie hinterlegt ist.
> fix: clearer warning ui

- layouts/partials/sidemenu.html
> fix: sidemenu

- content/generalInformation.de.md
- content/generalInformation.en.md
A section that contains links to other services providing information about FIP
> feat: Add additional useful resources

- content/operator/eurostar/index.de.md
- content/operator/eurostar/index.en.md
> fix: add eurostar pricing

- content/operator/eurostar/index.de.md
- content/operator/eurostar/index.en.md
Afaik International Rail Ltd has no connection to National Rail
> fix: Eurostar booking is via International Rail Ltd, not National Rail

- archetypes/operator/index.de.md
- archetypes/operator/index.en.md
- content/operator/dsb/index.de.md
- content/operator/dsb/index.en.md
- content/operator/ns/index.de.md
- content/operator/ns/index.en.md
- content/operator/renfe/index.de.md
- content/operator/renfe/index.en.md
- content/operator/sncb/index.de.md
- content/operator/sncb/index.en.md
- content/operator/zsr/index.de.md
- content/operator/zsr/index.en.md
Unify some content information in the files and remove differences in the content structure between operators.
> fix: unify some content information

- layouts/partials/image.html
Use `srcset` instead of individual sources: https://developer.mozilla.org/en-US/docs/Web/HTML/Guides/Responsive_images
> feat: Let the browser decide which image quality to load

- content/operator/eurostar/index.de.md
- content/operator/eurostar/index.en.md
Add information for Eurostar London Connections
> fix: add london international

- assets/sass/navigation.scss
wrap country items in navigation
> feat: wrap country items in navigation

- content/booking/cfl_phone/index.de.md
- content/booking/cfl_phone/index.en.md
- content/booking/uk_mail/index.de.md
- content/booking/uk_mail/index.en.md
- content/operator/eurostar/index.de.md
- content/operator/eurostar/index.en.md
Eurostar has some problems selling the route to London by telephone lately. So we should add the CFL Hotline as Backup.
> fix: eurostar booking problem

- assets/sass/navigation.scss
In Firefox-Browser the multi-columns was not displayed correctly.
> fix: country multi column

- layouts/_default/_markup/render-link.html
> fix: Detect absolute links with the same hostname as internal links

- assets/sass/navigation.scss
- assets/sass/print.scss
- assets/sass/styles.scss
- layouts/_default/baseof.html
- layouts/_default/list.html
- layouts/country/single.html
- layouts/news/list.html
- layouts/news/single.html
- layouts/operator/single.html
A different approach after #193 had to be reverted.
> fix: Avoid layout shift when scrollbar appears

- assets/sass/footer.scss
> fix: Overlay language switcher over other content

- content/operator/sncb/index.de.md
- content/operator/sncb/index.en.md
- content/operator/sncb/index.fr.md
> fix: no SNCB board surcharge for FIP tickets

- LICENSE
> fix: Change license to Attribution-ShareAlike 4.0 International

- content/booking/cp-ticket-office/index.de.md
- content/booking/cp-ticket-office/index.en.md
- content/booking/cp-ticket-office/index.fr.md
- content/country/portugal/index.de.md
- content/country/portugal/index.en.md
- content/country/portugal/index.fr.md
- content/operator/cp/index.de.md
- content/operator/cp/index.en.md
- content/operator/cp/index.fr.md
> fix: updated all links to cp.pt bc of the website-relaunch

- content/operator/ns/index.de.md
- content/operator/ns/index.en.md
- content/operator/ns/index.fr.md
- content/operator/sncb/index.de.md
- content/operator/sncb/index.en.md
- content/operator/sncb/index.fr.md
> feat: Add Eurocity train information for NS and SNCB operators

- content/booking/eurostar-ticket-office/index.de.md
- content/booking/eurostar-ticket-office/index.en.md
- content/booking/eurostar-ticket-office/index.fr.md
- content/operator/eurostar/index.de.md
- content/operator/eurostar/index.en.md
- content/operator/eurostar/index.fr.md
Update the Eurostar Telephone. You can only book tickets for Eurostar Red there. I also added the Eurostar Ticket Office.
> fix: update Eurostar booking information

- content/operator/euskotren/index.de.md
Only added it to the German variant since the article is available in German only.
> feat: Add Zugpost link to Euskotren page
