README.md
assets/js/highlightHeadline.js
assets/js/main.js
assets/sass/fonts.scss
assets/sass/main.scss
assets/sass/sidemenu.scss
assets/sass/styles.scss
assets/sass/toc.scss
content/_index.de.md
content/_index.en.md
content/country/netherlands/index.de.md
content/country/netherlands/index.en.md
content/operator/eurostar/index.en.md
content/operator/ns/index.de.md
content/operator/ns/index.en.md
hugo.yaml
i18n/de.yaml
i18n/en.yaml
layouts/country/single.html
layouts/operator/single.html
layouts/partials/sidemenu.html
layouts/partials/toc.html
layouts/shortcodes/highlight.html

feat: add side menu and text styling

---

assets/sass/styles.scss
content/operator/zsr/index.de.md
content/operator/zsr/index.en.md
layouts/_default/baseof.html
layouts/_default/single.html
layouts/country/single.html
layouts/operator/single.html
layouts/partials/_ico.html
layouts/partials/head.html

- Updated the ZSSK Intercity Content
- Updated the ZSSK Sources und Footnotes
- Updated the pagefind icons in the results overview
- Added an icon in the title of the operator and country side
- Added a text highlighting searched terms on the content pages
- Update Chrome Android theme color

fix: update zssk and minor design improvements

---

assets/sass/stage.scss

The search overflowed the picture on larger screens. This should fix it.
Before:
After:
It's probably better to set the max-width on a parent element and let the search + picture inherit from it, but for some reason it didn't properly work when I tried it.

fix: Search overflows on large screens

---

CONTRIBUTING.md

A `CONTRIBUTING.md` is considered a good practice for open source projects. It helps developers to get started quickly.
It clearly doesn't replace the already existing guide for content contributors. The `CONTRIBUTING.md` is only focused on developers.
I couldn't find instructions how to get started, so I just added some. Feel free to extend them. 
An English version for the `CONTRIBUTING.md` is sufficient imho.

docs: Add `CONTRIBUTING.md`

---

netlify.toml

This PR adds the foundation for PR previews using Netlify. Netlify is a cloud computing company that offers fast & easy deployment of pages. The free plan is sufficient, no credit card is required and as far as I know, pull request previews don't even count for the limit.
Using the provided configuration, a preview is built for each opened PR automatically. 
An example can be seen here, where I tested the functionality: https://github.com/MoritzWeber0/fipguide.github.io/pull/1#issuecomment-2839887790 
This avoids cases like "It works on my machine" and also makes reviews easier. You don't to set up the local environment every time for small changes, instead you can just check the result.
The only disadvantage is that someone with permissions in this repository has to create a Netlify …

ci: Add PR previews with Netlify

---

netlify.toml

Some links didn't work without the base url.

fix: Specify baseURL for netlify deployments

---

archetypes/country.en.md
content/country/belgium/index.en.md
content/country/slovakia/index.en.md
content/privacy.en.md
i18n/en.yaml

Instead of operator, use operators as plural form.

fix: Use correct plural of operator

---

content/country/netherlands/index.de.md
content/country/netherlands/index.en.md
content/snippets/wip.de.md
content/snippets/wip.en.md
layouts/shortcodes/snippet.html

This adds a new shortcut called snippet. It can be used to include reusable markdown content. 
In this PR, a new snippet "wip" (work in progress) was added. To do so, two new files "content/snippets/wip.en.md" and "content/snippets/wip.de.md" were added. To include the snippet, just use the shortcut "snipped" like: 
```
{{< snippet wip >}}
```
The specific "wip" snippet informs about an incomplete page. It has been applied to the (so far) empty Netherlands page.

feat: Add new snippet shortcut and note to incomplete pages

---

assets/sass/styles.scss

This is just a proposal because in my opinion the margins of the anchors / dividers are too large. But it's an personal opinion, so happy to hear other voices :) 
Before: 
After:

fix: Reduce margins for anchors

---

assets/sass/fonts.scss
hugo.yaml
i18n/de.yaml
i18n/en.yaml
layouts/_default/_markup/render-link.html
layouts/partials/icon.html
layouts/partials/link.html
layouts/partials/sidemenu.html

Add a link to report issues directly in the sidemenu. Corresponding labels are auto-added to the report.
Depends on https://github.com/fipguide/fipguide.github.io/pull/96. Do not merge before https://github.com/fipguide/fipguide.github.io/pull/96 is merged!

feat: Report issues on pages directly from sidemenu

---

archetypes/operator.de.md
archetypes/operator.en.md
content/operator/dsb/index.de.md
content/operator/dsb/index.en.md
content/operator/eurostar/index.de.md
content/operator/eurostar/index.en.md
content/operator/sncb/index.de.md
content/operator/sncb/index.en.md
content/operator/zsr/index.de.md
content/operator/zsr/index.en.md
content/snippets/wip.de.md
content/snippets/wip.en.md
layouts/shortcodes/expander.html
layouts/shortcodes/highlight.html

Fixing the rendering of footnodes in shortcodes.
Compare:
https://github.com/jmooring/hugo-testing/tree/hugo-forum-topic-43832
https://discourse.gohugo.io/t/isolation-of-links-and-footnotes-inside-codeblocks/43795/7

fix: #79 footnodes in shortcodes

---

.github/pull_request_template.md
archetypes/country.de.md
archetypes/country.en.md
archetypes/default.md
archetypes/operator.de.md
archetypes/operator.en.md
assets/sass/content.scss
content/country/belgium/index.de.md
content/country/belgium/index.en.md
content/country/netherlands/index.de.md
content/country/netherlands/index.en.md
content/country/slovakia/index.de.md
content/country/slovakia/index.en.md
content/generalInformation.de.md
content/generalInformation.en.md
content/operator/eurostar/index.de.md
content/operator/eurostar/index.en.md
content/operator/ns/index.de.md
content/operator/ns/index.en.md
content/operator/sncb/index.de.md
content/operator/sncb/index.en.md
content/operator/zsr/index.de.md
content/operator/zsr/index.en.md
hugo.yaml
layouts/partials/icon.html
layouts/partials/updateDate.html

It's not longer needed to provide the "date" attribute in the page metadata. If it's not provided, the information will be auto-fetched from Git.
Related to #95
The disadvantage with the auto-updated date is that also minor changes like updated grammar, spelling etc. will also update the "last updated" field.

feat: Auto-fetch "last updated" from Git history

---

content/operator/sncb/index.en.md

Just a small fix for wrongly places points in the English version of the Eurostar page.

fix(eurostar): Wrongly places points

---

layouts/shortcodes/expander.html

Fixes an issue where `</div>` was rendered as code block in some expanders.
Unfortunately, indentation code blocks are quite annoying in CommonMark, but I couldn't find a way to disable it.
So without indentation seems to be the way to go.

fix: HTML rendering in expander

---

i18n/de.yaml
i18n/en.yaml
layouts/partials/stage.html

Let users open the search via the CTRL + K keyboard shortcut.

feat: Make search usable via keyboard (CTRL + K)

---

.gitignore
layouts/404.html

Style and content of the 404 (english version) has been modified

67 add styling for 404 page

---

layouts/country/single.html
layouts/operator/single.html
layouts/partials/logo.html

`data-pagefind-meta="img"` is not a valid option, therefore it was ignored and the first picture of the page was used.

fix: Detection of image in pagefind was broken

---

layouts/shortcodes/expander.html

The span in #145 was only added to the print version (due to a rebase / merge). This adds it to the normal version for which it was originally planned.
It fixes the following display issue:

fix: Handle search highlight in expander summary correctly

---

.github/workflows/deploy.yaml
assets/sass/styles.scss
layouts/_default/_markup/render-image.html
layouts/country/single.html
layouts/operator/single.html
layouts/partials/image.html
layouts/partials/stage.html

- Add error handling for pictures that are not found
- Use image partial in render-image hook
- Remove unused code

refactor: Rewrite parts of image rendering

---

layouts/_default/single.html

fix: Remove "Last updated" from general pages

---

layouts/partials/image.html

fix: Use empty alt label on decorative images

---

assets/sass/sidemenu.scss
layouts/partials/sidemenu.html

fix: aside backlink positioning

---

assets/sass/anchorlink.scss

Instead of having the copy icon directly after the text (which produced some issues with multi-line texts), always place the the copy icon on the right side. It's easier to reach for right-handed people.
Not 100% sure if the link icon is still recognized with a connection to the title, so happy to hear any feedback.
Resolves #49

fix: Always place the copy icon on the right side on mobile

---

.pre-commit-config.yaml
i18n/de.yaml
i18n/en.yaml

This avoids merge conflicts in i18n files if two diverging branches add a new key to the file.

ci: Sort i18n yaml files alphabetically

---

assets/sass/anchorlink.scss
assets/sass/print.scss
assets/sass/styles.scss
layouts/country/single.html
layouts/operator/single.html
layouts/partials/content.html

Dividers can be added more easily in any HTML template via `<hr class="o-divider">` instead of restricting them to `a-anchorlink`. Required for https://github.com/fipguide/fipguide.github.io/pull/178.

refactor: Replace `::before` for dividers with explicit hr

---

layouts/_default/_markup/render-link.html

By default, Hugo only allows using `http:`, `https:`, and `mailto:`. URLs using other schemes are replaced with `#ZgotmplZ`. To allow using `tel:`, we have to declare it as safe using `| safeURL`. This marks every URL as safe which should be fine, since all content inside the repo is trusted.
See https://gohugo.io/functions/safe/url/ for more info.
Closes #185
Originally merged into booking-shortcode in https://github.com/fipguide/fipguide.github.io/pull/189, but it's relevant for main already. Credit goes to @zusorio, I just reopened the PR.

fix: Mark `tel:` links as safe

---

content/country/_index.de.md
content/country/_index.en.md
content/operator/_index.de.md
content/operator/_index.en.md
layouts/partials/headMeta.html

- removed metaDescription-logic
- optimized descriptions of country- & operator-page

fix: meta description & text optimizations

---

assets/sass/styles.scss

This reverts commit 85ceeee4991c6c58775f12f20768aae8898959d1.
It breaks the relative positioning of the aside element.

Revert "fix: Avoid page jumping when scrollbar appears"

---

layouts/partials/updateDate.html

fix: Remove "Last updated" from news articles (only show date instead)

---

layouts/partials/stage.html

So far, the search dialog could be closed by clicking outside of the search element, but only if no text was entered. If text was entered in the input field, it was no longer possible. This commit closes the search on click outside, independent of entered text in the search field.

fix: Close search when clicking outside of search area

---

assets/sass/anchorlink.scss

fix: Always show snack bar in front of other elements

---

assets/sass/navigation.scss
assets/sass/styles.scss
assets/sass/teaser.scss
content/operator/_index.de.md
content/operator/_index.en.md
layouts/_default/baseof.html
layouts/_default/home.html
layouts/_default/rss.xml
layouts/news/list.html
layouts/partials/head.html
layouts/partials/header.html
layouts/partials/shortcut-tile.html
layouts/partials/sidemenu.html
layouts/partials/strip-material-icons.html
layouts/partials/teaser.html
layouts/partials/toc.html

I tried to split the different parts into different commits, so that we can easily take out some individual parts.

feat: Implement enhancements for new design

---

assets/sass/headings.scss
assets/sass/navigation.scss
assets/sass/styles.scss
layouts/partials/search-slot.html

This improves the usage of the search, since it's always placed at the top of the screen when using it. Search results are no longer hidden below a keyboard or the end of the screen.

fix: Scroll to search when using it

---

layouts/partials/booking.html
layouts/partials/prefix-footnotes.html

Otherwise, the anchor ids are conflicting when a booking section with footnotes is embedded into an operator page.

fix: Scope footnotes to their corresponding booking section

---

layouts/partials/image.html

This allows browsers to render the highest possible image quality.
Resolves #235.

fix: Add original image quality to srcset

---

content/operator/sbb/index.fr.md

Follow-up for https://github.com/fipguide/fipguide.github.io/pull/242, where one train category in the French translation was missing.

fix: Add missing train icon for SBB Regio in French translation

---

assets/js/interactiveMap.js
assets/js/main.js
assets/sass/interactiveMap.scss
assets/sass/main.scss
assets/sass/styles.scss
i18n/de.yaml
i18n/en.yaml
i18n/fr.yaml
layouts/country/list.html
layouts/partials/menu.html
package-lock.json
package.json
static/map_europe.svg

This is just the initial draft for an interactive map that can be used to navigate the countries on the countries page, in addition to the list of countries.
It's the foundation for the map and can be extended by indicating the FIP rating via background color, show additional information on hover or click etc.
Resolves #135
In a later step, we could optimize the behavior and add the CSS classes to available countries in the SVG during build time, not with JavaScript during run time. However, this is more complex, we need to parse the SVG in Go templates.

feat: Add interactive map to navigate countries

---

assets/sass/interactiveMap.scss

The z-index of the country map was too high, so it was visible in front of the mobile menu. I fixed that.

Fixed z-index in country map

---

assets/sass/teaser.scss

Avoid a white border in the news overview. The border is still shown in the dark mode.
Before:
After:

fix: Remove image borders for teasers in light mode

---

assets/sass/styles.scss
content/booking/db-website-fip-db/index.de.md
content/booking/db-website-fip-db/index.en.md
content/booking/db-website-fip-db/index.fr.md
content/booking/db-website-fip-international/index.de.md
content/booking/db-website-fip-international/index.en.md
content/booking/db-website-fip-international/index.fr.md

Resolves #338 
The new style avoids column breaking and displays the additional information in a smaller font for better overview:

fix: Do not break list item text into next column

---

layouts/partials/icon.html

Do not translate the icon font as this leads to a broken display of icons:

fix: Do not translate icons

---

assets/sass/styles.scss

One additional commit for #351 to improve the list formatting that I broke in the restructuring:

fix: Improve list formatting in print view of country overview

---

assets/sass/expander.scss

Full-width tables look a bit better:
Before:
Removing the margin-right on inside elements of the expanders, they were introduced because of https://github.com/fipguide/fipguide.github.io/issues/142, but it doesn't seem to be an issue anymore.

feat: Use full-width tables in expanders

---

assets/sass/headings.scss

After headings, text is expected that should be rendered on the same page. Avoid page breaks like here: 
Unfortunately, the option is not properly considered in Firefox ([bug report](https://bugzilla.mozilla.org/show_bug.cgi?id=775617) opened 13 years ago :D), but in Chrome it works.

fix: Avoid page break after heading in print version
